version: '3.8'

services:
  facebook-scraper:
    build: .
    container_name: facebook-scraper
    volumes:
      # Mount output directory พร้อมสร้างโฟลเดอร์ตามวันที่
      - ./data/outputs:/usr/src/app/output
      # Mount groups.json (read-only)
      - ./groups.json:/usr/src/app/groups.json:ro
    environment:
      - TZ=Asia/Bangkok
      - NODE_ENV=production
      # Configuration
      - OUTPUT_DIR=/usr/src/app/output
      - MERGE_EXISTING=true
      - MAX_HISTORY_DAYS=30
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge

# Structure ที่จะถูกสร้าง:
# ./data/outputs/
#   ├── latest/
#   │   ├── all_posts_data.json
#   │   ├── success_keyword.json
#   │   └── failed_groups.json
#   ├── history/
#   │   ├── 2025-10-19_14-30-00/
#   │   ├── 2025-10-19_18-45-00/
#   │   └── ...
#   └── merged_data.json (combined from all history)