version: '3.8'

services:
  facebook-scraper:
    build: .
    container_name: facebook-scraper
    volumes:
      - ./data/outputs:/usr/src/app/output
    environment:
      - TZ=Asia/Bangkok
      - NODE_ENV=production
      # Output Configuration
      - OUTPUT_DIR=/usr/src/app/output
      - MERGE_EXISTING=true
      - MAX_HISTORY_DAYS=30
      # Groups Source (API URL)
      - GROUPS_SOURCE=http://192.168.88.186:3002/app/groups.json
      - SKIP_FIRST_GROUP=false
      # Facebook Credentials
      - FB_EMAIL=test.face112@gmail.com
      - FB_PASSWORD=passW@rd
    restart: unless-stopped
    ports:
      - "4000:4000"
    extra_hosts:
      # ถ้า API อยู่ในเครื่องเดียวกัน
      - "host.docker.internal:host-gateway"